--Facilitador SELECT
SELECT * FROM Pessoa;
SELECT * FROM Sala;
SELECT * FROM Aluno;
SELECT * FROM Notas;
SELECT * FROM Disciplina;
SELECT * FROM Sala_Disc;
SELECT * FROM Professor;
SELECT * FROM Diretor;
--END-- Facilitador DROP TABLE

--Facilitador DROP TABLE
DROP TABLE Pessoa;
DROP TABLE Sala;
DROP TABLE Aluno;
DROP TABLE Notas;
DROP TABLE Disciplina;
DROP TABLE Sala_Disc;
DROP TABLE Professor;
DROP TABLE Diretor;
--END-- Facilitador DROP TABLE