-- CREATE TABLE Exercicio (
-- 	ID_PESSOA SERIAL NOT NULL,
-- 	NM_PESSOA VARCHAR(255),
-- 	ID_CPF VARCHAR(30)
-- );

-- DROP TABLE EXERCICIO

-- INSERT INTO EXERCICIO (NM_PESSOA, ID_CPF) VALUES ('VICTOR', '08618351903');
-- INSERT INTO EXERCICIO (NM_PESSOA, ID_CPF) VALUES ('VINICIUS', '0000000000');
-- INSERT INTO EXERCICIO (NM_PESSOA, ID_CPF) VALUES ('ALGUEM AI', '111111111');

DROP TABLE ASSINANTE;
DROP TABLE RAMO_ASSINANTE;
DROP TABLE TIPO_ASSINANTE;
DROP TABLE ENDERECO;
DROP TABLE TELEFONE;
DROP TABLE MUNICIPIO;

CREATE TABLE ASSINANTE (
	CD_ASSINANTE SERIAL NOT NULL,
	NM_ASSINANTE VARCHAR(255)
);

CREATE TABLE RAMO_ASSINANTE(
	CD_RAMO SERIAL NOT NULL,
	DS_RAMO VARCHAR(255)
);

CREATE TABLE TIPO_ASSINANTE(
	CD_TIPO SERIAL NOT NULL,
	DS_TIPO VARCHAR(255)
);

CREATE TABLE ENDERECO (
	CD_ENDERECO SERIAL NOT NULL,
	DS_ENDERECO VARCHAR(255),
	COMPLEMENTO VARCHAR(100),
	BAIRRO VARCHAR(50),
	CEP VARCHAR(10)
);

CREATE TABLE TELEFONE(
	CD_FONE SERIAL NOT NULL,
	DDD VARCHAR(4),
	N_FONE VARCHAR(30)
);

CREATE TABLE MUNICIPIO(
	CD_MUNICIPIO SERIAL NOT NULL,
	DS_MUNICIPIO VARCHAR(255)
);

INSERT INTO ASSINANTE (NM_ASSINANTE) VALUES ('Victor');

INSERT INTO RAMO_ASSINANTE (DS_RAMO) VALUES ('aaaaaa');

SELECT * FROM ASSINANTE;
SELECT * FROM RAMO_ASSINANTE;
SELECT * FROM TIPO_ASSINANTE;
SELECT * FROM ENDERECO;
SELECT * FROM TELEFONE;
SELECT * FROM MUNICIPIO;

--Criar Relação 
ALTER TABLE ASSINANTE ADD COLUMN CD_RAMO SERIAL NOT NULL;

ALTER TABLE RAMO_ASSINANTE ADD PRIMARY KEY (CD_RAMO);

ALTER TABLE ASSINANTE
ADD CONSTRAINT FK_CD_RAMO_1
FOREIGN KEY (CD_RAMO) REFERENCES RAMO_ASSINANTE(CD_RAMO)
ON UPDATE CASCADE
ON DELETE NO ACTION;
